#!/bin/sh
# join.sh — contributor one-shot setup (the mechanical part of onboarding).
#
# Usage:
#   sh scripts/join.sh <owner/repo>
#
# Runs the prerequisite checks (git, gh+auth, uv; elan only for Lean
# projects) and the Choir install, and points this folder's AGENTS.md and
# CLAUDE.md at the manual. Reads the project's prover first, so a project
# for one prover never installs another's toolchain. Idempotent: fix what
# it flags and re-run until it reports READY. The behavioral contract for
# the agent driving this is docs/agents/CONTRIBUTOR.md.
#
# Portability: POSIX sh. Native: macOS / Linux / *BSD. Windows: WSL only
# (the script detects MSYS/Cygwin/Git-Bash and says so). User-space
# installers (uv, elan) are run automatically; system packages (git, gh)
# are instruct-only — no sudo is ever invoked.

set -u

usage() { echo "usage: sh $0 <owner/repo>" >&2; }

REPO=""
while [ $# -gt 0 ]; do
  case "$1" in
    -*)
      echo "unknown option: $1" >&2
      usage
      exit 1 ;;
    *)
      if [ -z "$REPO" ]; then
        REPO="$1"
      else
        echo "unexpected argument: $1" >&2
        exit 1
      fi ;;
  esac
  [ $# -gt 0 ] && shift
done
if [ -z "$REPO" ]; then
  usage
  exit 1
fi

case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*)
    echo "Native Windows is not supported. Use WSL:" >&2
    echo "    wsl --install -d Ubuntu" >&2
    echo "then re-run this script inside the WSL shell." >&2
    exit 1 ;;
esac

CHOIR_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
FAILS=0
flag() { echo "ACTION NEEDED: $1"; FAILS=$((FAILS + 1)); }

# Tools installed to user space later in this run live here.
USER_PATH="$PATH"
PATH="$HOME/.local/bin:$HOME/.elan/bin:$PATH"

# iCloud Drive syncs ~/Documents and ~/Desktop when "Desktop & Documents
# Folders" is on, and marks files it manages with the macOS hidden flag.
# Python skips a hidden `.pth`, so a virtualenv under those folders stops
# importing at unpredictable times — including long after a setup that
# reported READY.
icloud_synced_root() {
  _cloud="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
  [ -d "$_cloud" ] || return 1
  for _name in Documents Desktop; do
    [ -L "$_cloud/$_name" ] || continue
    case "$CHOIR_DIR/" in
      "$HOME/$_name"/*) echo "$HOME/$_name"; return 0 ;;
    esac
  done
  return 1
}

# This checkout's environment when it cannot live beside the checkout. The
# name carries a checksum of the checkout path: the environment holds an
# editable install pointing at ONE checkout, so two checkouts sharing one
# would silently run each other's code.
venv_target() {
  echo "$HOME/.choir/venvs/$(basename "$CHOIR_DIR")-$(printf '%s' "$CHOIR_DIR" | cksum | cut -d' ' -f1)"
}

# Move the environment out of the synced folder and link it back, so uv and
# every `choir` call still find `$CHOIR_DIR/.venv`. An existing environment
# at the target is kept: it is this checkout's, and rebuilding it is the
# repair path's job, not setup's. Flags survive a move, so clear them once
# on arrival.
relocate_venv() {
  _target=$(venv_target)
  # Already a link to a real directory: wherever it points is not the synced
  # folder, which is all this has to achieve. Repointing it would strand
  # whatever the link was deliberately aimed at.
  if [ -L "$CHOIR_DIR/.venv" ]; then
    [ -d "$CHOIR_DIR/.venv" ] && return 0
    rm -f "$CHOIR_DIR/.venv"
  fi
  mkdir -p "$(dirname "$_target")" || return 1
  if [ -d "$CHOIR_DIR/.venv" ]; then
    if [ -d "$_target" ]; then
      rm -rf "$CHOIR_DIR/.venv"
    else
      mv "$CHOIR_DIR/.venv" "$_target" || return 1
    fi
  fi
  mkdir -p "$_target" || return 1
  rm -rf "$CHOIR_DIR/.venv"
  ln -s "$_target" "$CHOIR_DIR/.venv" || return 1
  if command -v chflags >/dev/null 2>&1 && [ -d "$_target" ]; then
    chflags -R nohidden "$_target" 2>/dev/null || true
  fi
  return 0
}

# `choir` on PATH, execing through $CHOIR_DIR/.venv so relocating or
# rebuilding the environment leaves it working. `choir update` refreshes
# the same file (client/update.py).
BIN_DIR="$HOME/.local/bin"
install_entry_point() {
  mkdir -p "$BIN_DIR" || return 1
  _tmp="$BIN_DIR/.choir.$$"
  cat > "$_tmp" <<EOF || return 1
#!/bin/sh
# Generated by Choir setup. Edits are lost on the next run.
_v="$CHOIR_DIR/.venv/bin/choir"
[ -x "\$_v" ] || {
  echo "choir: no environment at $CHOIR_DIR/.venv — re-run Choir setup" >&2
  exit 127
}
exec "\$_v" "\$@"
EOF
  chmod +x "$_tmp" && mv -f "$_tmp" "$BIN_DIR/choir"
}

if _synced=$(icloud_synced_root); then
  if relocate_venv; then
    echo "ok: environment at $(readlink "$CHOIR_DIR/.venv") (outside $_synced, which iCloud syncs)"
  else
    flag "this checkout is inside $_synced, which iCloud Drive is syncing, and
        the environment could not be relocated to $(venv_target). iCloud marks
        files hidden as it syncs them, Python skips a hidden .pth file, and
        \`choir\` then fails with ModuleNotFoundError. Move the checkout
        outside ~/Documents and ~/Desktop — Choir's default is
        ~/.choir/checkout — and re-run."
  fi
fi

# --- system packages: check only, never sudo ---------------------------
if command -v git >/dev/null 2>&1; then
  echo "ok: git"
else
  flag "install git (macOS: xcode-select --install | Debian/Ubuntu: apt install git | Fedora: dnf install git | Arch: pacman -S git | FreeBSD: pkg install git)"
fi

if command -v gh >/dev/null 2>&1; then
  if gh auth status >/dev/null 2>&1; then
    echo "ok: gh (authenticated)"
  else
    flag "authenticate GitHub: run \`gh auth login\` (interactive)"
  fi
else
  flag "install GitHub CLI: https://cli.github.com (macOS: brew install gh), then \`gh auth login\`"
fi

# --- project prover: gates the toolchain install, so a project for one
# prover never pulls in another's tools. Read from the repo's
# .choir/project.toml; default lean4 (matches the gate) when unreadable.
PROVER=lean4
if command -v gh >/dev/null 2>&1; then
  _pt="$(gh api "repos/$REPO/contents/.choir/project.toml" \
           -H "Accept: application/vnd.github.raw" 2>/dev/null \
         | grep -oE '^[[:space:]]*prover[[:space:]]*=[[:space:]]*"[^"]*"' \
         | head -1 | sed -E 's/.*"([^"]*)".*/\1/')"
  case "$_pt" in
    lean4|isabelle|rocq) PROVER="$_pt" ;;
  esac
fi
echo "ok: project prover = $PROVER"

# --- user-space installers: run automatically ---------------------------
if command -v uv >/dev/null 2>&1; then
  echo "ok: uv"
else
  echo "installing uv (user-space) ..."
  if curl -LsSf https://astral.sh/uv/install.sh | sh >/dev/null 2>&1 \
     && command -v uv >/dev/null 2>&1; then
    echo "fixed: uv installed"
  else
    flag "install uv manually: https://docs.astral.sh/uv/getting-started/installation/"
  fi
fi

if [ "$PROVER" = "lean4" ]; then
  if command -v elan >/dev/null 2>&1; then
    echo "ok: elan"
  else
    echo "installing elan (user-space, no default toolchain — projects pin their own) ..."
    if curl -sSf https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh \
         | sh -s -- -y --default-toolchain none >/dev/null 2>&1 \
       && command -v elan >/dev/null 2>&1; then
      echo "fixed: elan installed"
    else
      flag "install elan manually: https://github.com/leanprover/elan"
    fi
  fi
else
  echo "note: project prover is $PROVER — Choir will not install Lean's elan."
  echo "      Ensure the $PROVER toolchain is on your PATH yourself (isabelle:"
  echo "      an Isabelle release; rocq: opam + rocq-prover + dune). The worker"
  echo "      builds with the project's own build command (see CHOIR.md)."
fi

# --- Choir itself --------------------------------------------------------
if command -v uv >/dev/null 2>&1; then
  echo "syncing Choir ($CHOIR_DIR) ..."
  if (cd "$CHOIR_DIR" && uv sync --extra dev >/dev/null 2>&1); then
    echo "ok: choir synced"
  else
    flag "\`uv sync --extra dev\` failed in $CHOIR_DIR — run it there and read the error"
  fi
fi

# --- smoke-test the CLI --------------------------------------------------
# A synced tree is not the same as a working one: `uv sync` reports success
# for an editable install it already considers satisfied, even when that
# install no longer resolves — every `choir` call then dies with
# ModuleNotFoundError. Only running the CLI catches that, so run it and
# read the error instead of discarding it.
if command -v uv >/dev/null 2>&1; then
  CLI_ERR=$( (cd "$CHOIR_DIR" && uv run choir worker list "$REPO" 2>&1 >/dev/null) )
  if [ $? -eq 0 ]; then
    echo "ok: can reach $REPO"
  elif echo "$CLI_ERR" | grep -q 'ModuleNotFoundError'; then
    # The environment resolves the package but cannot import it. Repeated
    # rebuilds can leave the editable install pointing nowhere, and
    # `--reinstall-package choir` does not recover it: it reports a
    # successful reinstall and the import still fails. Replacing the
    # environment does, and it costs a few seconds from the lockfile, so
    # do it here rather than hand the user a cure that will not work.
    echo "repairing the Choir environment ($CHOIR_DIR/.venv) ..."
    # Only ever this checkout's own environment, proven by its manifest
    # being there, and rebuildable from the lockfile beside it. When the
    # environment is relocated, rebuild what the link points at and relink —
    # deleting the link alone would put the replacement back in the synced
    # folder the relocation exists to avoid.
    if [ -f "$CHOIR_DIR/pyproject.toml" ]; then
      if [ -L "$CHOIR_DIR/.venv" ]; then
        rm -rf "$(readlink "$CHOIR_DIR/.venv")"
        relocate_venv
      else
        rm -rf "$CHOIR_DIR/.venv"
      fi
    fi
    if (cd "$CHOIR_DIR" && uv sync --extra dev >/dev/null 2>&1) &&
       (cd "$CHOIR_DIR" && uv run choir worker list "$REPO" >/dev/null 2>&1); then
      echo "ok: environment rebuilt; can reach $REPO"
    else
      flag "\`choir\` is installed but not importable, and rebuilding
        $CHOIR_DIR/.venv did not fix it. Run this and read the error:
        (cd $CHOIR_DIR && uv sync --extra dev && uv run choir worker list $REPO)"
    fi
  else
    flag "\`choir worker list $REPO\` failed — $(echo "$CLI_ERR" | head -1)"
  fi
fi

# Against the user's PATH, not the one this script prepended to for its
# own use: checking after that would confirm the assumption, not test it.
if install_entry_point; then
  _found=$(PATH="$USER_PATH"; command -v choir 2>/dev/null) || _found=""
  if [ "$_found" = "$BIN_DIR/choir" ]; then
    echo "ok: choir on PATH ($BIN_DIR/choir)"
  elif [ -n "$_found" ]; then
    flag "the \`choir\` on your PATH is $_found, not $BIN_DIR/choir.
        Remove it, or order PATH so $BIN_DIR comes first."
  else
    flag "$BIN_DIR is not on your PATH, so \`choir\` will not be found.
        Add it (\`export PATH=\"\$HOME/.local/bin:\$PATH\"\` in your shell's
        startup file), or call $BIN_DIR/choir by its full path."
  fi
else
  flag "could not write the \`choir\` entry point to $BIN_DIR"
fi

# The manual is the worker's contract, and an agent that never reads it
# guesses at the rules it is judged by. The joining prompt names it, but a
# prompt does not survive a context compaction: the summary keeps that you
# are a Choir contributor and drops the path. What the harness does re-read
# from disk is this folder's CLAUDE.md and AGENTS.md, so the pointer goes
# there — in both, since CLAUDE.md is the file the harness is documented to
# load and AGENTS.md is not. Unlike the orchestrator there is nothing else
# durable to record, so neither file has to defer to the other: the task,
# its target, and the statement all live in the workspace the claim builds,
# and `choir` regenerates them.
#
# These files are the contributor's. The block is prepended and whatever is
# already in the file is kept below it, and a file already carrying its block
# is left alone, so re-running this script changes nothing.
POINTER="Read the manual \`$CHOIR_DIR/docs/agents/CONTRIBUTOR.md\` and work
tasks on \`$REPO\` by it."
AGENTS_BLOCK="$POINTER"
CLAUDE_BLOCK="$POINTER"

ensure_pointer() {
  _file="$1"; _marker="$2"; _block="$3"
  if [ -f "$_file" ]; then
    grep -qF "$_marker" "$_file" && return 1
    _tmp="$_file.choir.$$"
    { printf '%s\n\n' "$_block"; cat "$_file"; } > "$_tmp" || return 2
    mv -f "$_tmp" "$_file" || return 2
  else
    printf '%s\n' "$_block" > "$_file" || return 2
  fi
  return 0
}

# A worker clones Choir into this folder, so it is normally outside any
# repo; `.git/info/exclude` is local and uncommitted and covers the case
# where it is not.
exclude_locally() {
  _git_dir=$(git rev-parse --git-dir 2>/dev/null) || return 0
  for _name in AGENTS.md CLAUDE.md; do
    grep -qxF "/$_name" "$_git_dir/info/exclude" 2>/dev/null && continue
    mkdir -p "$_git_dir/info" && printf '/%s\n' "$_name" >> "$_git_dir/info/exclude"
  done
}

_wrote=""
for _name in AGENTS.md CLAUDE.md; do
  case "$_name" in AGENTS.md) _block="$AGENTS_BLOCK" ;; *) _block="$CLAUDE_BLOCK" ;; esac
  ensure_pointer "$PWD/$_name" "docs/agents/CONTRIBUTOR.md" "$_block"
  case "$?" in
    0) _wrote="$_wrote $_name" ;;
    2) flag "could not write the manual pointer to $PWD/$_name" ;;
  esac
done
if [ -n "$_wrote" ]; then
  exclude_locally
  echo "ok: manual pointer added to$_wrote in $PWD"
else
  echo "ok: manual pointer already in AGENTS.md and CLAUDE.md"
fi

# --- verdict -------------------------------------------------------------
echo
if [ "$FAILS" -gt 0 ]; then
  echo "NOT READY: $FAILS item(s) flagged above. Fix them and re-run:"
  echo "    sh $0 $REPO"
  exit 1
fi

echo "READY. Claim a task and work it:"
echo "    choir worker list $REPO"
echo "Your contract from here: $CHOIR_DIR/docs/agents/CONTRIBUTOR.md"
