#!/bin/sh
# orchestrator-init.sh — overseer-machine one-shot setup (the mechanical part).
#
# Usage:
#   sh scripts/orchestrator-init.sh <owner/repo>
#
# Checks prerequisites (git, gh+auth with push rights, uv), syncs Choir, points
# the working folder's AGENTS.md and CLAUDE.md at the playbook, and tells the
# orchestrator agent where to pick up. Deliberately does NOT write
# ~/.choir/orchestrator.toml — interviewing the overseer for that is the
# agent's job (docs/agents/orchestrator-setup.md § "Your local config").
#
# Run it from the folder the orchestrator agent will be launched in.
#
# Portability: POSIX sh; macOS / Linux / *BSD native, Windows via WSL.
# No sudo is ever invoked.

set -u

REPO="${1:-}"
if [ -z "$REPO" ]; then
  echo "usage: sh $0 <owner/repo>" >&2
  exit 1
fi

case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*)
    echo "Native Windows is not supported. Use WSL:" >&2
    echo "    wsl --install -d Ubuntu" >&2
    echo "then re-run this script inside the WSL shell." >&2
    exit 1 ;;
esac

CHOIR_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
FAILS=0
flag() { echo "ACTION NEEDED: $1"; FAILS=$((FAILS + 1)); }

USER_PATH="$PATH"
PATH="$HOME/.local/bin:$PATH"

# iCloud Drive syncs ~/Documents and ~/Desktop when "Desktop & Documents
# Folders" is on, and marks files it manages with the macOS hidden flag.
# Python skips a hidden `.pth`, so a virtualenv under those folders stops
# importing at unpredictable times — including long after a setup that
# reported READY.
icloud_synced_root() {
  _cloud="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
  [ -d "$_cloud" ] || return 1
  for _name in Documents Desktop; do
    [ -L "$_cloud/$_name" ] || continue
    case "$CHOIR_DIR/" in
      "$HOME/$_name"/*) echo "$HOME/$_name"; return 0 ;;
    esac
  done
  return 1
}

# This checkout's environment when it cannot live beside the checkout. The
# name carries a checksum of the checkout path: the environment holds an
# editable install pointing at ONE checkout, so two checkouts sharing one
# would silently run each other's code.
venv_target() {
  echo "$HOME/.choir/venvs/$(basename "$CHOIR_DIR")-$(printf '%s' "$CHOIR_DIR" | cksum | cut -d' ' -f1)"
}

# Move the environment out of the synced folder and link it back, so uv and
# every `choir` call still find `$CHOIR_DIR/.venv`. An existing environment
# at the target is kept: it is this checkout's, and rebuilding it is the
# repair path's job, not setup's. Flags survive a move, so clear them once
# on arrival.
relocate_venv() {
  _target=$(venv_target)
  # Already a link to a real directory: wherever it points is not the synced
  # folder, which is all this has to achieve. Repointing it would strand
  # whatever the link was deliberately aimed at.
  if [ -L "$CHOIR_DIR/.venv" ]; then
    [ -d "$CHOIR_DIR/.venv" ] && return 0
    rm -f "$CHOIR_DIR/.venv"
  fi
  mkdir -p "$(dirname "$_target")" || return 1
  if [ -d "$CHOIR_DIR/.venv" ]; then
    if [ -d "$_target" ]; then
      rm -rf "$CHOIR_DIR/.venv"
    else
      mv "$CHOIR_DIR/.venv" "$_target" || return 1
    fi
  fi
  mkdir -p "$_target" || return 1
  rm -rf "$CHOIR_DIR/.venv"
  ln -s "$_target" "$CHOIR_DIR/.venv" || return 1
  if command -v chflags >/dev/null 2>&1 && [ -d "$_target" ]; then
    chflags -R nohidden "$_target" 2>/dev/null || true
  fi
  return 0
}

# `choir` on PATH, execing through $CHOIR_DIR/.venv so relocating or
# rebuilding the environment leaves it working. `choir update` refreshes
# the same file (client/update.py).
BIN_DIR="$HOME/.local/bin"
install_entry_point() {
  mkdir -p "$BIN_DIR" || return 1
  _tmp="$BIN_DIR/.choir.$$"
  cat > "$_tmp" <<EOF || return 1
#!/bin/sh
# Generated by Choir setup. Edits are lost on the next run.
_v="$CHOIR_DIR/.venv/bin/choir"
[ -x "\$_v" ] || {
  echo "choir: no environment at $CHOIR_DIR/.venv — re-run Choir setup" >&2
  exit 127
}
exec "\$_v" "\$@"
EOF
  chmod +x "$_tmp" && mv -f "$_tmp" "$BIN_DIR/choir"
}

if _synced=$(icloud_synced_root); then
  if relocate_venv; then
    echo "ok: environment at $(readlink "$CHOIR_DIR/.venv") (outside $_synced, which iCloud syncs)"
  else
    flag "this checkout is inside $_synced, which iCloud Drive is syncing, and
        the environment could not be relocated to $(venv_target). iCloud marks
        files hidden as it syncs them, Python skips a hidden .pth file, and
        \`choir\` then fails with ModuleNotFoundError. Move the checkout
        outside ~/Documents and ~/Desktop — Choir's default is
        ~/.choir/checkout — and re-run."
  fi
fi

if command -v git >/dev/null 2>&1; then
  echo "ok: git"
else
  flag "install git (macOS: xcode-select --install | Debian/Ubuntu: apt install git | Fedora: dnf install git | Arch: pacman -S git | FreeBSD: pkg install git)"
fi

if command -v gh >/dev/null 2>&1; then
  if gh auth status >/dev/null 2>&1; then
    echo "ok: gh (authenticated)"
  else
    flag "authenticate GitHub: run \`gh auth login\` (interactive)"
  fi
else
  flag "install GitHub CLI: https://cli.github.com (macOS: brew install gh), then \`gh auth login\`"
fi

if command -v uv >/dev/null 2>&1; then
  echo "ok: uv"
else
  echo "installing uv (user-space) ..."
  if curl -LsSf https://astral.sh/uv/install.sh | sh >/dev/null 2>&1 \
     && command -v uv >/dev/null 2>&1; then
    echo "fixed: uv installed"
  else
    flag "install uv manually: https://docs.astral.sh/uv/getting-started/installation/"
  fi
fi

if command -v uv >/dev/null 2>&1; then
  echo "syncing Choir ($CHOIR_DIR) ..."
  if (cd "$CHOIR_DIR" && uv sync --extra dev >/dev/null 2>&1); then
    echo "ok: choir synced"
  else
    flag "\`uv sync --extra dev\` failed in $CHOIR_DIR — run it there and read the error"
  fi

  # A synced tree is not a working one: `uv sync` reports success for an
  # editable install it already considers satisfied, even when that
  # install no longer resolves, and then every `choir` call dies with
  # ModuleNotFoundError.
  #
  # Probe with the installed command, not `python -c "import choir_cli"`:
  # `python -c` puts the working directory on `sys.path`, so run from the
  # checkout it imports the source tree directly and reports health
  # whatever state the install is in. The console script has no such
  # fallback, which is why it is the thing that breaks for the user.
  if ! "$CHOIR_DIR/.venv/bin/choir" >/dev/null 2>&1; then
    echo "repairing the Choir environment ($CHOIR_DIR/.venv) ..."
    # When the environment is relocated, rebuild what the link points at and
    # relink — deleting the link alone would put the replacement back in the
    # synced folder the relocation exists to avoid.
    if [ -f "$CHOIR_DIR/pyproject.toml" ]; then
      if [ -L "$CHOIR_DIR/.venv" ]; then
        rm -rf "$(readlink "$CHOIR_DIR/.venv")"
        relocate_venv
      else
        rm -rf "$CHOIR_DIR/.venv"
      fi
    fi
    if (cd "$CHOIR_DIR" && uv sync --extra dev >/dev/null 2>&1) &&
       "$CHOIR_DIR/.venv/bin/choir" >/dev/null 2>&1; then
      echo "ok: environment rebuilt"
    else
      flag "\`choir\` is installed but not importable, and rebuilding
        $CHOIR_DIR/.venv did not fix it. Run this and read the error:
        (cd $CHOIR_DIR && uv sync --extra dev && ./.venv/bin/choir)"
    fi
  else
    echo "ok: choir is importable"
  fi
fi

# Against the user's PATH, not the one this script prepended to for its
# own use: checking after that would confirm the assumption, not test it.
if install_entry_point; then
  _found=$(PATH="$USER_PATH"; command -v choir 2>/dev/null) || _found=""
  if [ "$_found" = "$BIN_DIR/choir" ]; then
    echo "ok: choir on PATH ($BIN_DIR/choir)"
  elif [ -n "$_found" ]; then
    flag "the \`choir\` on your PATH is $_found, not $BIN_DIR/choir.
        Remove it, or order PATH so $BIN_DIR comes first."
  else
    flag "$BIN_DIR is not on your PATH, so \`choir\` will not be found.
        Add it (\`export PATH=\"\$HOME/.local/bin:\$PATH\"\` in your shell's
        startup file), or call $BIN_DIR/choir by its full path."
  fi
else
  flag "could not write the \`choir\` entry point to $BIN_DIR"
fi

# Project state: existing repo means resume; missing means bootstrap.
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if gh repo view "$REPO" >/dev/null 2>&1; then
    if [ "$(gh api "repos/$REPO" --jq .permissions.push 2>/dev/null)" = "true" ]; then
      echo "ok: $REPO exists and you have push rights — RESUME it (read the roadmap; never re-bootstrap)"
    else
      flag "no push rights on $REPO — the orchestrator needs push/merge access"
    fi
  else
    echo "ok: $REPO does not exist yet — bootstrap with scripts/new-project.sh"
  fi
fi

# The playbook is the orchestrator's contract, and an agent that never reads
# it runs the loop from guesswork. A launch prompt cannot carry it: a context
# compaction keeps a summary, and a summary keeps the command's name, not the
# document. What the harness does re-read from disk is the launch folder's
# CLAUDE.md and AGENTS.md — so the pointer goes there. The agent writes its
# session brief above this line once the overseer has been interviewed
# (docs/agents/orchestrator-setup.md § "Your session brief"), which is why
# CLAUDE.md sends the reader to AGENTS.md rather than repeating the pointer:
# CLAUDE.md is the file documented to load, and the brief is in the other one.
#
# These files are the overseer's. The block is prepended and whatever is
# already in the file is kept below it, and a file already carrying its block
# is left alone, so re-running this script changes nothing.
AGENTS_BLOCK="Read the playbook \`$CHOIR_DIR/docs/agents/ORCHESTRATOR.md\` and act
as the orchestrator."
CLAUDE_BLOCK="Read AGENTS.md in this folder and follow it."

ensure_pointer() {
  _file="$1"; _marker="$2"; _block="$3"
  if [ -f "$_file" ]; then
    grep -qF "$_marker" "$_file" && return 1
    _tmp="$_file.choir.$$"
    { printf '%s\n\n' "$_block"; cat "$_file"; } > "$_tmp" || return 2
    mv -f "$_tmp" "$_file" || return 2
  else
    printf '%s\n' "$_block" > "$_file" || return 2
  fi
  return 0
}

# Keeping them untracked is the point: a worker reading the orchestrator's
# instructions is a worker following the wrong manual. The launch folder is
# normally outside any repo, and `.git/info/exclude` is local and uncommitted,
# so it covers the case where it is not.
exclude_locally() {
  _git_dir=$(git rev-parse --git-dir 2>/dev/null) || return 0
  for _name in AGENTS.md CLAUDE.md; do
    grep -qxF "/$_name" "$_git_dir/info/exclude" 2>/dev/null && continue
    mkdir -p "$_git_dir/info" && printf '/%s\n' "$_name" >> "$_git_dir/info/exclude"
  done
}

_wrote=""
for _pair in "AGENTS.md|docs/agents/ORCHESTRATOR.md" "CLAUDE.md|Read AGENTS.md in this folder"; do
  _name=${_pair%%|*}
  _mark=${_pair#*|}
  case "$_name" in AGENTS.md) _block="$AGENTS_BLOCK" ;; *) _block="$CLAUDE_BLOCK" ;; esac
  ensure_pointer "$PWD/$_name" "$_mark" "$_block"
  case "$?" in
    0) _wrote="$_wrote $_name" ;;
    2) flag "could not write the playbook pointer to $PWD/$_name" ;;
  esac
done
if [ -n "$_wrote" ]; then
  exclude_locally
  echo "ok: playbook pointer added to$_wrote in $PWD"
else
  echo "ok: playbook pointer already in AGENTS.md and CLAUDE.md"
fi

echo
if [ "$FAILS" -gt 0 ]; then
  echo "NOT READY: $FAILS item(s) flagged above. Fix them and re-run:"
  echo "    sh $0 $REPO"
  exit 1
fi

echo "READY. Orchestrator agent: read $CHOIR_DIR/docs/agents/orchestrator-setup.md"
echo "first. Its first step: interview your overseer and write"
echo "~/.choir/orchestrator.toml (never commit or quote it). The loop"
echo "itself is docs/agents/ORCHESTRATOR.md, your operating manual."
